### ISSUE TITLE
Effecting latest news section

### ISSUE THREAD

**Issue by Med-MG** [Abbassihraf/P-curiosity-LAB#14]
https://github.com/Abbassihraf/P-curiosity-LAB/blob/00e530c5449a28a971aa77c8a5e29a9a5c1815f1/src/sass/pages/_aboutUs.scss#L981

**Comment by Abbassihraf** [comment]
what's wrong?

**Comment by Abbassihraf** [comment]
Ok, I'll fixed it.

**Comment by Abbassihraf** [comment]
Done check it.
