### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by Abbassihraf** [Abbassihraf/P-curiosity-LAB#16]
Js file applied just in HOME page, whenI add another file JS for another page, It'll not work properly,
If you go to the console, this message appears : **Uncaught TypeError: Cannot read property 'addEventListener' of null**

**Comment by Abbassihraf** [comment]
@Med-MG : We're waiting for the solution

**Comment by Med-MG** [comment]
![Capture_error](https://user-images.githubusercontent.com/46869106/85293814-c5ce9b80-b495-11ea-8d9a-7943929807c6.PNG)
here is the problem , tell me where is the class btnMore ?

**Comment by Med-MG** [comment]
https://github.com/Abbassihraf/P-curiosity-LAB/commit/e7d74a0b2555aadd9d393594451996314096812b
