### ISSUE TITLE
The last notes to be taken into consideration

### ISSUE THREAD

**Issue by Abbassihraf** [Abbassihraf/P-curiosity-LAB#27]
- [ ] - First part of the home page (the blue is too strong in contrast with PCL logo I would suggest a lighter  blue or white) 
- [x] - Reduce the place taken (in the part where the video is)
- [x] - Darker grey for the tittle of “Mission” 
- [x] - Separation line between “What we offer” - “Our events” - “Latest News”
- [x] - Reduce space between the sections 
- [x] - Add more background visuals if possible. 
- [x] - Last part of the home page (less space between the points/elements).
- [x] - Logo should be a little bit bigger.
- [x] - Navbar links.

**Comment by Med-MG** [comment]
we should have a meeting and discuss these changes 🧐

**Comment by Abbassihraf** [comment]
@Med-MG : **Check out the task list**
