### ISSUE TITLE
Hero header background problem

### ISSUE THREAD

**Issue by Abbassihraf** [Abbassihraf/P-curiosity-LAB#32]
Try to click on the links at the navbar, It'll not work with you, because the background is dominant.
For this, you've to add this property : **_z-index: -1;_**  on this class **_.header-webinar-video__img_**

**Comment by Med-MG** [comment]
okey i'll fix it

**Comment by Abbassihraf** [comment]
Sounds good.

**Comment by Abbassihraf** [comment]
@Med-MG 
When you solve **the problem**, don't forget to close issue.

**Comment by Med-MG** [comment]
I did solve the problem, i sent a closing order in the commit it just didn't go through for some reason
